### ISSUE TITLE
Error on collapse/expand item in "Monolog" tab

### ISSUE THREAD

**Issue by vjik** [buggregator/frontend#187]
Console:

```
YzCi6Sqx.js:14 TypeError: f.preventDefault is not a function
    at O (BwlufsCQ.js:2:5636)
    at Ut (YzCi6Sqx.js:14:38)
    at nt (YzCi6Sqx.js:14:109)
    at ih (YzCi6Sqx.js:14:2201)
    at a (BwlufsCQ.js:2:2659)
    at Ut (YzCi6Sqx.js:14:38)
    at nt (YzCi6Sqx.js:14:109)
    at HTMLButtonElement.n (YzCi6Sqx.js:18:7325)
```

**Comment by Kreezag** [comment]
Fixed.
